### ISSUE TITLE
PopupList.getInstance().initPopupList初始化

### ISSUE THREAD

**Issue by smarthityou** [shangmingchao/PopupList#1]
大神，你在初始化的时候只考虑了是listview和gridview情况，而我的项目是点击的是一个普通的view，为了实现同样的效果，在你的PopupList.java中initPopupList方法中将AbsListView→View    而对应的showPopupWindow方法中不要（position  点击的列表项在列表数据集中的位置）这个参数，就实现了只要是view的控件都能事项popup效果。

**Comment by shangmingchao** [comment]
@smarthityou 嗯，谢谢。我可以考虑新增一个针对普通View的popup菜单效果。
