### ISSUE TITLE
弹出框变形

### ISSUE THREAD

**Issue by star-andy** [shangmingchao/PopupList#2]
<img width="257" alt="qq20161021-0 2x" src="https://cloud.githubusercontent.com/assets/15726024/19590116/bfbb5f30-97a2-11e6-8184-019591ab74aa.png">

没找到原因 如果方面可以留个qq吗？

**Comment by shangmingchao** [comment]
嗯，从截图上看，您的字体比较大，而padding比较小，所以导致了截图中的情况。所以您可以通过`popupList.setTextSizePixel(float)`方法减小字体，或者修改`PopupList.java`文件中的padding值增大padding。
这里确实缺少相关方法，我会尽快完善，我的邮箱smchao1993@163.com，欢迎交流。

**Comment by star-andy** [comment]
我用你之前最开始的版本[http://www.voidcn.com/blog/shangmingchao/article/p-4917451.html](url)  修改成我要的效果没出现上面的问题

**Comment by shangmingchao** [comment]
嗯，我只在CSDN上写过，不过已经修改了，不知道为什么之前的版本会出现在别的网站上。
之前是使用RecyclerView实现的，感觉没有必要。建议你还是用最新的PopupList这个文件吧，代码简洁，便于维护。

**Comment by star-andy** [comment]
额  可以是我却感觉之前的代码阅读性比较高  新版本的虽然简介但是都在一个文件里阅读起来有些困难

**Comment by shangmingchao** [comment]
嗯，也可以。那我先close这个issue了，如果您有更好的实现，可以open欢迎随时交流。

**Comment by star-andy** [comment]
好的    最好再加一个分割线的margin哈
![image](https://cloud.githubusercontent.com/assets/15726024/19632032/0fa4a8f6-99d5-11e6-9877-497c0e603bd4.png)

**Comment by shangmingchao** [comment]
嗯
