### ISSUE TITLE
请问dalao在recyclerView中如何使用这个控件

### ISSUE THREAD

**Issue by lm11000** [shangmingchao/PopupList#3]
我用长按监听回调到activity中使用这个控件,他会重写longclick事件...这就很尴尬了.
另外,如果我想时刻变动popublist里面的string内容,bind了以后就改不了了啊...longtouch直接走bin里面的回调了

**Comment by lm11000** [comment]
补充一下.因为我不确定每次点击的是哪个item,而点击的每个数据都可能不同,所以如果想根据数据动态设置listString的话就做不到了,因为longtouch直接就走bind了

**Comment by shangmingchao** [comment]
你可以看一下这个[Sample](https://github.com/shangmingchao/PopupList/blob/master/samples/src/main/java/com/frank/sample/SecondaryActivity.java#L57)，这种情况你可以在每个item的长按事件处理中使用`showPopupListWindow`方法主动来显示弹出框，而不是使用`bind`方法。  
至于每个item显示不同的ListString，最后一个参数可以使用`PopupList.AdapterPopupListListener`，在其中的`formatText`方法中根据你的业务逻辑返回对应的String就可以了。read [Wiki](https://github.com/shangmingchao/PopupList/wiki/%E8%AF%A6%E7%BB%86%E9%85%8D%E7%BD%AE)。

**Comment by lm11000** [comment]
谢谢dalao.问题解决了.
又出现了一个新的问题,请问一下PopupList可以使用垂直方式显示吗?
我把popupListContainer.setOrientation(LinearLayout.HORIZONTAL);改成Vertical,结果直接不显示了

**Comment by shangmingchao** [comment]
目前没有计划支持竖直列表，因为我了解的竖直列表的使用场景一般是`PopupMenu`。你希望的竖直方向的弹出框样式是怎样的呢？

**Comment by lm11000** [comment]
显示方式应该差不了很多吧.
设计做了一个竖直的界面.左边是图片右边是TextView,然后竖直的形式铺下来.
我这边给它两用一个LinearLayout给它们封到一起了.可是在显示的时候出了问题

**Comment by shangmingchao** [comment]
我并没有理解你说的场景，也不清楚你说显示的时候出了什么问题。这种常规的横向气泡式上下文菜单很多应用都有，都是横向的。竖直的[上下文菜单](https://developer.android.com/guide/topics/ui/menus.html#context-menu)最常见的(如微信的长按操作)是这种：  
![menu-context](https://developer.android.com/images/ui/menu-context.png)  
也就是说，这种场景更适合使用[ContextMenu](https://developer.android.com/reference/android/view/ContextMenu.html)或[PopupMenu](https://developer.android.com/reference/android/widget/PopupMenu.html)而不是PopupList。

**Comment by lm11000** [comment]
谢谢!我就说怎么设计看上去那么别扭,我明天找她说去.
她是真真的就是做了个竖的PopupList,哈哈...

**Comment by shangmingchao** [comment]
嗯，竖的上下文菜单通常都是这个样式和实现方式。如果没什么问题我就close这个issue了。
