### ISSUE TITLE
为嘛捆绑在recyclerview上没用，那个view是从传给适配器的

### ISSUE THREAD

**Issue by zyx7454210** [shangmingchao/PopupList#4]
List<String> popupMenuItemList = new ArrayList<>();
        popupMenuItemList.add("编辑");
        popupMenuItemList.add("删除");
        PopupList popupList=new PopupList(context);
        ////设置点击出泡泡框
        popupList.bind(view, popupMenuItemList, new PopupList.PopupListListener() {
            @Override
            public boolean showPopupList(View adapterView, View contextView, int contextPosition) {
                return true;
            }

            @Override
            public void onPopupListClick(View contextView, int contextPosition, int position) {
                Log.v("tag","哈哈");
            }
        });

**Comment by shangmingchao** [comment]
这个view是ItemView么？有没有事件监听？如果存在事件冲突可以选择手动为view `setOnLongClickListener/setOnItemLongClickListener`然后使用`showPopupListWindow`方法而不是直接使用`bind`方法([Sample](https://github.com/shangmingchao/PopupList/blob/master/samples/src/main/java/com/frank/sample/SecondaryActivity.java#L54))，详见[Wiki](https://github.com/shangmingchao/PopupList/wiki/%E8%AF%A6%E7%BB%86%E9%85%8D%E7%BD%AE)及[Sample](https://github.com/shangmingchao/PopupList/blob/master/samples/src/main/java/com/frank/sample/SecondaryActivity.java#L57)。
