### ISSUE TITLE
当个数过多时没法展示全？

### ISSUE THREAD

**Issue by zhanzengyu** [shangmingchao/PopupList#6]
@shangmingchao 
你好，请问可以支持翻页吗？
当个数多的时候会显示不全，这个如何解决呢？

**Comment by shangmingchao** [comment]
菜单项个数比较多的时候使用这种样式是否合适？还是利用`HorizontalScrollView`让列表可以水平滚动？如果让列表可以水平滚动可以指定列表最大宽度并将列表[容器View](https://github.com/shangmingchao/PopupList/blob/master/library/PopupList.java#L209)使用`HorizontalScrollView`包裹即可

**Comment by zhanzengyu** [comment]
@shangmingchao 
感谢，按照你的思路确实可以。
